config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'

  resources :categories, only: [:index, :show]
  resources :connections, only: [:create, :destroy]
  resources :items, except: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    resources :transactions, only: [:destroy, :create, :update]
    get "/friends" => "users#friends"
  end

  get "/users/:id/cart" => "users#cart"
  get '/csv_example' => 'application#csv_example'

  post 'import/items' => 'items#import' do
    collection { post :import }
  end

  post "/users/:id/checkout" => 'users#checkout'
  post "/users/:id/clear_cart" => 'users#clear_cart'

  get "/search" => 'users#search'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }
  validates_confirmation_of :password

  has_many :connections_as_friender, class_name: "Connection", foreign_key: "friender_id"
  has_many :connections_as_friendee, class_name: "Connection", foreign_key: "friendee_id"
  has_many :friendees, through: :connections_as_friender
  has_many :frienders, through: :connections_as_friendee
  has_many :items_for_sale, class_name: "Item", foreign_key: "seller_id"
  has_many :sales, through: :items_for_sale, source: :transactions
  has_many :purchases, class_name: "Transaction", foreign_key: "buyer_id"
  has_many :purchased_items, through: :purchases, source: :item


  def friends
    self.frienders + self.friendees
  end

  def five_friends
    if self.friends.length >= 5
      self.friends.sample(5)
    else
      self.friends.sample(self.friends.length)
    end
  end

  def cart
    self.purchases.where("purchased = 'false'")
  end

  def past_orders
    self.purchases.where("purchased = 'true'")
  end

  def is_friends_with?(friendee)
    !!connection(friendee)
  end

  def connection(friendee)
    if !!Connection.find_by(friender_id: self.id, friendee_id: friendee.id)
      return Connection.find_by(friender_id: self.id, friendee_id: friendee.id)
    elsif !!Connection.find_by(friender_id: friendee.id, friendee_id: self.id)
      return Connection.find_by(friender_id: friendee.id, friendee_id: self.id)
    else
      return nil
    end
  end

  def sold_items
    self.sales.where("purchased = 'true'")
  end

  def checkout
    self.cart.map do |sale|
      sale.update_attributes(purchased: true)
      sale.item.decrement!(:count, by = sale.quantity)
    end
  end

  def friends_activities_feed
    self.friends_activities.sort_by { |activity| activity.created_at }.reverse.take(10)
  end

  def friends_activities
    activities_with_duplicates = self.friends_purchases + self.friends_sales
    activities_with_duplicates.uniq
  end

  def friends_purchases
    friends_purchases = []
    self.friends.each do |friend|
      friend.purchases.each do |purchase|
        friends_purchases << purchase
      end
    end
    friends_purchases
  end

  def friends_sales
    friends_sales = []
    self.friends.each do |friend|
      friend.sales.each do |sale|
        friends_sales << sale
      end
    end
    friends_sales
  end

  def clear_cart
    self.cart.map do |sale|
      sale.destroy
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      render "users/show"
    else
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  def cart
    @cart = current_user.cart
  end

  def friends
    @user = User.find_by(id: params[:user_id])
  end

  def checkout
    @user = current_user
    @user.checkout
    redirect_to '/'
  end

  def clear_cart
    @user = current_user
    @user.clear_cart
    redirect_to '/'
  end

  def search
    @user = User.find_by_username(params[:name])
    @item = Item.find_by_name(params[:name])
    if @user
      redirect_to "/users/#{@user.id}"
    elsif @item
      redirect_to "/items/#{@item.id}"
    else
      redirect_to "/"
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friends_feed.html.erb
<div id="friends-feed">
  <h4><a href="/users/<%= @user.id %>/friends">Friends (<%= @user.friends.count %>)</a></h4>
  <ul>
    <% @user.five_friends.each do |friend| %>
      <li class="friends-list"><a href="/users/<%= friend.id %>"><%= friend.username %></a></li>
    <% end %>
  </ul>
</div>

app/views/users/cart.html.erb
<h1>Cart</h1>

<div class="cart-items">
  <% @cart.each do |cart_item| %>
    <h3><%= cart_item.item.name %></h3>
    <p>Price: $ <%= number_with_precision((cart_item.item.price_in_dollars * cart_item.quantity), precision: 2) %></p>
    <p>
      <%= form_for :transaction, url: "/users/#{current_user.id}/transactions/#{cart_item.id}", method: :put  do |f| %>
        <%= f.hidden_field :buyer_id, value: current_user.id %>
        <%= f.hidden_field :item_id, value: cart_item.item.id %>
        <%= f.label :quantity %>
        <%= f.select :quantity, (1..cart_item.item.count), selected: cart_item.quantity %><br><br>
        <%= f.submit "Update Quantity" %>
      <% end %>
    </p><br style="clear:both;">
    <%= link_to 'Remove', user_transaction_path(current_user, cart_item), method: :delete %>
  <% end %>
  <br><br>

  <%= link_to "Clear Cart", "/users/#{current_user.id}/clear_cart", method: :post %>
  <br>
  <%= form_tag("/users/#{current_user.id}/checkout", method: "post") do %>
    <%= submit_tag ("Checkout") %>
  <% end %>
</div>

app/views/users/friends.html.erb
<h1><%= @user.username %>'s friends (<%= @user.friends.count %>)</h1>

<ul>
  <% @user.friends.each do |friend| %>
    <li><a href="/users/<%= friend.id %>"><%= friend.username %></a></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= form_for :user, url:users_path do |f| %>
<%= render 'shared/error_messages' %>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>

   <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

   <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.submit "Register" %>
  </p>
<% end %>

app/views/users/show.html.erb
<% if logged_in? %>
  <div id="profile-page">
  <% if @user.id == current_user.id %>
    <% if !!@user.first_name %>
      <h1>Welcome back, <%= @user.first_name %></h1>
    <% else %>
      <h1>Welcome back!</h1>
    <% end %>

    <div class="row">
      <div class="col-md-8">
        <div id="past-orders-section">
          <h2 id="past-orders-header">Past Orders</h2>
          <% if !@user.past_orders.empty? %>
            <table id="past-orders-list">
              <% @user.past_orders.each do |purchase| %>
                <tr>
                  <td class="profile-items">
                    <h3><%= purchase.item.name %></h3>
                    <br>
                    Order made on <%= purchase.created_at.to_date %>
                    <br>
                    Quantity: <%= purchase.quantity %>
                    <br>
                    Price: $<%= number_with_precision(purchase.item.price_in_dollars * purchase.quantity, precision: 2) %>
                  </td>
                </tr>
              <% end %>
            </table>
          <% else %>
            <p>You haven't bought anything yet!</p>
          <% end %>
        </div>

        <div id="sold-items-section">
          <h2>Sold Items</h2>
          <% if !@user.sold_items.empty? %>
            <table id="sold-items-list">
              <% @user.sold_items.each do |sale| %>
                <tr>
                  <td class="profile-items">
                    <h3><%= sale.item.name %></h3>
                    <br>
                    Order made on <%= sale.created_at.to_date %>
                    <br>
                    Quantity: <%= sale.item.count %>
                    <br>
                    Price: $<%= number_with_precision(sale.item.price_in_dollars, precision: 2) %>
                  </td>
                </tr>
                <br>
              <% end %>
            </table>
          <% else %>
            <p>You haven't sold anything yet!</p>
          <% end %>
        </div>

        <div id="unsold-items-section">
          <h2>Unsold Items</h2>
          <table id="unsold-items-list">
            <% @user.items_for_sale.where("count>'0'").each do |item| %>
              <tr>
                <td class="profile-items">
                  <h3><%= item.name %></h3>
                  <br>
                  Listed on <%= item.created_at.to_date %>
                  <br>
                  Quantity: <%= item.count %>
                  <br>
                  Price: $<%= number_with_precision(item.price_in_dollars, precision: 2) %>
                  <br>
                  <%= link_to 'Remove item', item_path(item, user_id: @user.id),
                      method: :delete %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>

      </div>

      <div class="col-md-4">
        <%= render 'users/friends_feed' %>

        <div class="upload-csv">
          <h2>Sell more items!</h2>
          <p>Upload a CSV with a list of items that you would like to sell.</p>
          <p>Please be sure to include the following categories: name, description, unit, price (in cents), categories, and count.</p>
          <p>Please also be sure to separate an item's categories with a semicolon (no space).</p>
          <p><a href="/csv_example">Here</a> is a good example.</p>
          <%= render 'shared/error_messages' %>
          <%= form_tag import_items_path, multipart: true do %>
          <%= file_field_tag :file %>
          <%= submit_tag "Import CSV" %>
          <% end %>
        </div>
      </div>

    </div>
  <% else %>
    <div class="current-user-page">
      <h1>This is the profile page of <%= @user.username %></h1>

      <% if current_user.is_friends_with?(@user) %>
        <%= link_to "Unfriend", connection_path(current_user.connection(@user), user_id: @user.id),
            method: :delete %>

        <div id="past-orders-section">
          <h2 id="past-orders-header">Past Orders</h2>
          <table id="past-orders-list">
            <% @user.past_orders.each do |purchase| %>
              <tr>
                <td class="profile-items">
                  <h3><%= purchase.item.name %></h3>
                  <br>
                  Order made on <%= purchase.created_at.to_date %>
                  <br>
                  Quantity: <%= purchase.item.count %>
                  <br>
                  Price: $<%= purchase.item.price %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      <% else %>
        <%= form_for Connection.new do |f| %>
          <%= hidden_field_tag "connection[friendee_id]", "#{@user.id}" %>
          <%= submit_tag("Add Friend") %>
        <% end %>
      <% end %>
    </div>
  <% end %>
  </div>
<% else %>
  <div class="row" id="profile-page">
    <h1>This is the profile page of <%= @user.username %></h1>
  </div>
<% end %>

</div>