config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'

  resources :categories, only: [:index, :show]
  resources :connections, only: [:create, :destroy]
  resources :items, except: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    resources :transactions, only: [:destroy, :create, :update]
    get "/friends" => "users#friends"
  end

  get "/users/:id/cart" => "users#cart"
  get '/csv_example' => 'application#csv_example'

  post 'import/items' => 'items#import' do
    collection { post :import }
  end

  post "/users/:id/checkout" => 'users#checkout'
  post "/users/:id/clear_cart" => 'users#clear_cart'

  get "/search" => 'users#search'
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :categories_items
  has_many :items, through: :categories_items
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(id: params[:id])
  end

end

app/views/categories/index.html.erb
<h1>Departments</h1>

<div id="categories">
  <ul>
    <% @categories.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
    <% end %>
  </ul>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<div id="category-items">
  <ul>
    <% @category.items.order(:updated_at).each do |item| %>
      <li><%= link_to item.name, item_path(item) %></li><br>
    <% end %>
  </ul>
</div>