config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'

  resources :categories, only: [:index, :show]
  resources :connections, only: [:create, :destroy]
  resources :items, except: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    resources :transactions, only: [:destroy, :create, :update]
    get "/friends" => "users#friends"
  end

  get "/users/:id/cart" => "users#cart"
  get '/csv_example' => 'application#csv_example'

  post 'import/items' => 'items#import' do
    collection { post :import }
  end

  post "/users/:id/checkout" => 'users#checkout'
  post "/users/:id/clear_cart" => 'users#clear_cart'

  get "/search" => 'users#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories_item.rb
class CategoriesItem < ApplicationRecord
  validates :category_id, :item_id, presence: true
  validates :item_id, uniqueness: { scope: :category_id }

  belongs_to :category
  belongs_to :item
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :categories_items
  has_many :items, through: :categories_items
end

app/models/connection.rb
class Connection < ApplicationRecord
  validates :user_id, :friend_id, presence: false
  validates :friender_id, uniqueness: { scope: :friendee_id, message: "is already friends with this user" }
  validates :friendee_id, uniqueness: { scope: :friender_id, message: "is already friends with this user" }

  belongs_to :friender, class_name: "User"
  belongs_to :friendee, class_name: "User"
end

app/models/item.rb
class Item < ApplicationRecord
  require 'csv'

  validates :name, :description, :price, :count, :seller_id, :unit, presence: true

  has_many :categories_items
  has_many :categories, through: :categories_items
  belongs_to :seller, class_name: "User"
  has_many :transactions
  has_many :buyers, through: :transactions

  def self.import(file, user_id)
    CSV.foreach(file, headers: true) do |row|
      categories = row.delete("categories")[1]

      item = Item.new row.to_hash
      item.seller_id = user_id
      item.save
      categories.split(";").each do |category|
        category.downcase!.capitalize!
        item_category = Category.find_by(name: category)
        CategoriesItem.create(category_id: item_category.id, item_id: item.id) if !!item_category
      end
    end
  end

  def price_in_dollars
    self.price.to_f / 100
  end

  def self.spotlight
    Item.all.sample(5)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
  private
  def set_order_status
     self.order_status_id = 1
  end

  def update_subtotal
     self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items

  default_scope { where(active: true) }
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  validates :buyer_id, :item_id, :quantity, presence: true

  belongs_to :buyer, class_name: "User"
  belongs_to :item
  has_one :seller, through: :item
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }
  validates_confirmation_of :password

  has_many :connections_as_friender, class_name: "Connection", foreign_key: "friender_id"
  has_many :connections_as_friendee, class_name: "Connection", foreign_key: "friendee_id"
  has_many :friendees, through: :connections_as_friender
  has_many :frienders, through: :connections_as_friendee
  has_many :items_for_sale, class_name: "Item", foreign_key: "seller_id"
  has_many :sales, through: :items_for_sale, source: :transactions
  has_many :purchases, class_name: "Transaction", foreign_key: "buyer_id"
  has_many :purchased_items, through: :purchases, source: :item


  def friends
    self.frienders + self.friendees
  end

  def five_friends
    if self.friends.length >= 5
      self.friends.sample(5)
    else
      self.friends.sample(self.friends.length)
    end
  end

  def cart
    self.purchases.where("purchased = 'false'")
  end

  def past_orders
    self.purchases.where("purchased = 'true'")
  end

  def is_friends_with?(friendee)
    !!connection(friendee)
  end

  def connection(friendee)
    if !!Connection.find_by(friender_id: self.id, friendee_id: friendee.id)
      return Connection.find_by(friender_id: self.id, friendee_id: friendee.id)
    elsif !!Connection.find_by(friender_id: friendee.id, friendee_id: self.id)
      return Connection.find_by(friender_id: friendee.id, friendee_id: self.id)
    else
      return nil
    end
  end

  def sold_items
    self.sales.where("purchased = 'true'")
  end

  def checkout
    self.cart.map do |sale|
      sale.update_attributes(purchased: true)
      sale.item.decrement!(:count, by = sale.quantity)
    end
  end

  def friends_activities_feed
    self.friends_activities.sort_by { |activity| activity.created_at }.reverse.take(10)
  end

  def friends_activities
    activities_with_duplicates = self.friends_purchases + self.friends_sales
    activities_with_duplicates.uniq
  end

  def friends_purchases
    friends_purchases = []
    self.friends.each do |friend|
      friend.purchases.each do |purchase|
        friends_purchases << purchase
      end
    end
    friends_purchases
  end

  def friends_sales
    friends_sales = []
    self.friends.each do |friend|
      friend.sales.each do |sale|
        friends_sales << sale
      end
    end
    friends_sales
  end

  def clear_cart
    self.cart.map do |sale|
      sale.destroy
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @categories = Category.all
    @items = Item.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def import
    @user = User.find_by(id: session[:user_id])
    if !!params[:file]
      Item.import(params[:file].path, session[:user_id])
      redirect_to @user
    else
      @errors = ["Please choose a CSV file to import"]
      render 'users/show'
    end
  end

  def show
    @item = Item.find_by(id: params[:id])
  end

  def destroy
    @user = User.find_by(id: params[:user_id])
    item = Item.find_by(id: params[:id])
    item.destroy
    redirect_to @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      render "users/show"
    else
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  def cart
    @cart = current_user.cart
  end

  def friends
    @user = User.find_by(id: params[:user_id])
  end

  def checkout
    @user = current_user
    @user.checkout
    redirect_to '/'
  end

  def clear_cart
    @user = current_user
    @user.clear_cart
    redirect_to '/'
  end

  def search
    @user = User.find_by_username(params[:name])
    @item = Item.find_by_name(params[:name])
    if @user
      redirect_to "/users/#{@user.id}"
    elsif @item
      redirect_to "/items/#{@item.id}"
    else
      redirect_to "/"
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Panazon</title>
    <%= csrf_meta_tags %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="row">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a href="/"><%= image_tag("panazon.jpg", size: "200x45") %></a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <form class="navbar-form navbar-left" method="GET" action="/search">
              <div class="form-group">
                <input type="text" name="name" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
              <% if logged_in? %>
                <li><%= link_to "Log out", session_path(current_user), method: :delete %></li>
                <li><%= link_to "Profile", user_path(current_user) %></li>
                <li>
                  <a href="/users/<%= current_user.id %>/cart">
                    <span class="glyphicon glyphicon-shopping-cart glyphicon-align-left" aria-hidden="true"></span>
                  </a>
                </li>
              <% else %>
                <li><%= link_to "Log In", new_session_path %></li>
                <li><%= link_to "Register", new_user_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <div class="container-fluid" id="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @errors %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@errors.count, "error") %>.
    </div>
    <ul class="error_messages">
    <% @errors.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>